version: '3'

services:
  rust-server:
    build: .
    # image: scottliv/rust-server:latest
    # container_name: rust-server
    # restart: always
    ports:
      - "8080:8080"
    environment:
      APP_ENVIRONMENT: production