# Configures the default task to run
[tasks.default]
alias = "build-containers"

# Overrides the default build task
[tasks.build]
alias = "build-containers"

[tasks.build-server]
workspace = false
script = '''
docker build --rm -t scottliv/rust-server --target rust-server .
'''

[tasks.build-image-collector]
workspace = false
script = '''
docker build --rm -t scottliv/image_collector --target image_collector .
'''

[tasks.build-migration]
workspace = false
script = '''
docker build --rm -t scottliv/migration --target migration .
'''

[tasks.build-containers]
workspace = false
dependencies = ["build-server", "build-image-collector", "build-migration"]

[tasks.push-containers]
workspace = false
script = '''
echo "Not implemented yet."
'''

[tasks.delete-containers]
workspace = false
script = '''
docker image rm $(docker image ls -q --filter=label=service=rust-server)
docker image rm $(docker image ls -q --filter=label=service=image_collector)
'''
